<?php

/**
 * @file
 * Field hooks to implement a datetime field widgets and formatters.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function datetime_extras_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.datetime_extras':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Datetime Extras module provides a Date field widget and formatter.') . '</p>';
      return $output;
  }
}
